// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319103938_RemoveBrokenRealEstateRelation")]
    partial class RemoveBrokenRealEstateRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Models.Administration", b =>
                {
                    b.Property<int>("RemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfAdmin")
                        .HasColumnType("int");

                    b.HasKey("RemID");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("MyApi.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdministrationRemID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RemID")
                        .HasColumnType("int");

                    b.HasKey("CompanyID");

                    b.HasIndex("AdministrationRemID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MyApi.Models.CompanyReason", b =>
                {
                    b.Property<int>("CompanyReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyReasonID"));

                    b.Property<int>("CompaniesCompanyID")
                        .HasColumnType("int");

                    b.Property<int>("ReasonsReasonID")
                        .HasColumnType("int");

                    b.HasKey("CompanyReasonID");

                    b.HasIndex("CompaniesCompanyID");

                    b.HasIndex("ReasonsReasonID");

                    b.ToTable("CompanyReasons");
                });

            modelBuilder.Entity("MyApi.Models.Reason", b =>
                {
                    b.Property<int>("ReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonID");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("MyApi.Models.Shift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftID"));

                    b.Property<int?>("CompanyReasonID")
                        .HasColumnType("int");

                    b.Property<int>("ShopID")
                        .HasColumnType("int");

                    b.Property<string>("employee_phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("end_time")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("start_time")
                        .HasColumnType("time");

                    b.Property<string>("verification_code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftID");

                    b.HasIndex("CompanyReasonID");

                    b.HasIndex("ShopID");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("MyApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ShopID");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("MyApi.Models.Company", b =>
                {
                    b.HasOne("MyApi.Models.Administration", null)
                        .WithMany("Companies")
                        .HasForeignKey("AdministrationRemID");
                });

            modelBuilder.Entity("MyApi.Models.CompanyReason", b =>
                {
                    b.HasOne("MyApi.Models.Company", "Company")
                        .WithMany("CompanyReasons")
                        .HasForeignKey("CompaniesCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Reason", "Reason")
                        .WithMany("CompanyReasons")
                        .HasForeignKey("ReasonsReasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("MyApi.Models.Shift", b =>
                {
                    b.HasOne("MyApi.Models.CompanyReason", "CompanyReason")
                        .WithMany()
                        .HasForeignKey("CompanyReasonID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApi.Models.Shop", "Shop")
                        .WithMany("Shifts")
                        .HasForeignKey("ShopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyReason");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("MyApi.Models.Administration", b =>
                {
                    b.Navigation("Companies");

                });

            modelBuilder.Entity("MyApi.Models.Company", b =>
                {
                    b.Navigation("CompanyReasons");
                });

            modelBuilder.Entity("MyApi.Models.Reason", b =>
                {
                    b.Navigation("CompanyReasons");
                });

            modelBuilder.Entity("MyApi.Models.Shift", b =>
                {
                });

            modelBuilder.Entity("MyApi.Models.Shop", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
